export const Videos = [
  {
    id: "1",
    title: "Learn Vue 3 in 30 Minutes - Crash Course",
    channel: "Code Academy",
    views: "1.2M",
    uploaded: "2 weeks ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "30:12",
  },
  {
    id: "2",
    title: "Mastering SCSS - Complete Guide",
    channel: "Dev Simplified",
    views: "850K",
    uploaded: "1 month ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "45:23",
  },
  {
    id: "3",
    title: "Vue.js vs React - Which One Should You Learn?",
    channel: "Tech Explained",
    views: "500K",
    uploaded: "3 days ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "18:47",
  },
  {
    id: "4",
    title: "Building a YouTube Clone with Vue 3",
    channel: "Full Stack Dev",
    views: "120K",
    uploaded: "2 weeks ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "1:10:55",
  },
  {
    id: "5",
    title: "Understanding JavaScript Closures",
    channel: "JS Mastery",
    views: "900K",
    uploaded: "1 week ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "20:35",
  },
  {
    id: "6",
    title: "Quasar Framework - The Best UI for Vue?",
    channel: "Frontend Weekly",
    views: "670K",
    uploaded: "3 months ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "38:21",
  },
  {
    id: "7",
    title: "Docker for Developers - Full Course",
    channel: "DevOps School",
    views: "1.1M",
    uploaded: "5 months ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "2:15:40",
  },
  {
    id: "8",
    title: "Firebase Authentication in Vue 3",
    channel: "CodeWithMe",
    views: "220K",
    uploaded: "1 month ago",
    thumbnail: "https://via.placeholder.com/300x200",
    channelAvatar: "https://via.placeholder.com/50",
    duration: "55:10",
  },
];

export const youtubeSidebarItems = [
  {
    items: [
      { icon: "home", title: "Home" },
      { icon: "compass", title: "Explore" },
      { icon: "play-circle", title: "Shorts" },
      { icon: "subscriptions", title: "Subscriptions" },
    ],
  },
  {
    section: "Library",
    items: [
      { icon: "video-library", title: "Library" },
      { icon: "history", title: "History" },
      { icon: "smart-display", title: "Your Videos" },
      { icon: "schedule", title: "Watch Later" },
      { icon: "thumb-up", title: "Liked Videos" },
    ],
  },
  {
    section: "Subscriptions",
    items: [
      { icon: "account-circle", title: "Channel 1" },
      { icon: "account-circle", title: "Channel 2" },
      { icon: "account-circle", title: "Channel 3" },
      { icon: "account-circle", title: "Channel 4" },
    ],
  },
  {
    section: "Explore",
    items: [
      { icon: "whatshot", title: "Trending" },
      { icon: "music_note", title: "Music" },
      { icon: "gamepad", title: "Gaming" },
      { icon: "live_tv", title: "Live" },
      { icon: "emoji_events", title: "Sports" },
      { icon: "movie", title: "Movies & TV" },
      { icon: "newspaper", title: "News" },
      { icon: "lightbulb", title: "Learning" },
      { icon: "podcasts", title: "Podcasts" },
    ],
  },
  {
    section: "More from YouTube",
    items: [
      { icon: "movie", title: "Movies & TV" },
      { icon: "live-tv", title: "Live" },
      { icon: "gamepad", title: "Gaming" },
      { icon: "emoji-events", title: "Sports" },
      { icon: "library-music", title: "Music" },
      { icon: "podcasts", title: "Podcasts" },
    ],
  },
  {
    section: "Settings",
    items: [
      { icon: "settings", title: "Settings" },
      { icon: "flag", title: "Report history" },
      { icon: "help", title: "Help" },
      { icon: "feedback", title: "Send feedback" },
    ],
  },
];
